### ISSUE TITLE
Add Travis, CodeClimate, Gemnasium badges

### ISSUE THREAD

**Issue by herrtreas** [fromAtoB/kenny#7]
See title :)
- [ ] Travis
- [x] CodeClimate
- [ ] Gemnasium

**Comment by lucasrenan** [comment]
@herrtreas @actfong looks like I don't have enough permission to add travis and gemnasium support/badges.

**Comment by herrtreas** [comment]
@lucasrenan what do you need?

**Comment by lucasrenan** [comment]
@herrtreas probably access to those tools, then I can make the integration.

**Comment by herrtreas** [comment]
CodeClimate is enabled. Do we need Gemnasium?

**Comment by herrtreas** [comment]
Also Travis is enabled

```
[![Build Status](https://travis-ci.org/fromAtoB/kenny.svg?branch=master)](https://travis-ci.org/fromAtoB/kenny)```

**Comment by lucasrenan** [comment]
@herrtreas maybe we don't need gemnasium. we may try https://hakiri.io

**Comment by herrtreas** [comment]
Sounds good to me. @actfong ?

**Comment by actfong** [comment]
Sounds good to me too. Go for it @lucasrenan
